### ISSUE TITLE
Build errors when running `mvn clean install` command

### ISSUE THREAD

**Issue by Kneatrum** [samuelowino/mobile-translate#8]
Image
<img width="955" alt="Capture" src="https://github.com/samuelowino/mobile-translate/assets/21952262/3a6bfde8-b471-4326-8f3e-64df6ba03e43">
TXT file
[Error.txt](https://github.com/samuelowino/mobile-translate/files/14873435/Error.txt)

**Comment by Kneatrum** [comment]
@samuelowino I have tested this with the new changes. You're right. It's a separate problem

**Comment by samuelowino** [comment]
What is your Java version?

**Comment by samuelowino** [comment]
What is your Java version?

The OpenJDK team deperecated and later removed com.sun* and com.oracle* exported packages as of JDK 9 & later 10. This might be related to the problem you are facing. https://bugs.openjdk.org/browse/JDK-8191951

**Comment by Kneatrum** [comment]
I am using java version "22" 2024-03-19 and I see that downgrading to versions earlier than 9 isn't recommended. Which version are you using?

**Comment by Kneatrum** [comment]
The build was successful with JDK 11

**Comment by samuelowino** [comment]
Awesome, consider also juggling JDK version declarations in pom.xml to match your local version
