### ISSUE TITLE
xml parsing error

### ISSUE THREAD

**Issue by mwangidennis1** [samuelowino/mobile-translate#9]
## Description
The `fromXml` method in  XmlParserReader  class is throwing an error when trying to deserialize an XML file using JAXB.

## Steps to Reproduce
1. put some strings you want to translate in the  output.xml file 
2. run the ./mobile-translate.sh
3. Enter the  L (translation) then A (android) then the path to the output.xml path
4. observe the error
## Code
INFO: No strings found in xml
Exception in thread "main" java.lang.NullPointerException: Cannot read the array length because the return value of "com.owino.mobiletranslate.android.model.Resources.getStrings()" is null
        at com.owino.mobiletranslate.android.translate.AndroidTranslateFactory.translateResources(AndroidTranslateFactory.java:26)
        at com.owino.mobiletranslate.android.translate.AndroidTranslateFactory.getTranslatedResources(AndroidTranslateFactory.java:20)
        at com.owino.mobiletranslate.android.xml.XmlParserReader.executeXmlAndTranslationParser(XmlParserReader.java:31)
        at com.owino.mobiletranslate.android.AndroidTranslationProcessor.runTranslation(AndroidTranslationProcessor.java:10)
        at com.owino.mobiletranslate.TranslateApplication.main(TranslateApplication.java:28)

## expected behavior
The project will generate localised content and place them in the project/target directory, in the format of [locale].xml e.g de.xml or zh.xml.

## Actual behavior
The method 'executeXmlAndTranslationParser` in the class  XmlParserReader  expects a type of File as it inputs to its parameters but in the method main of TranslateApplication  we pass a type string which is the path to the xml file hence a type mismatch leading to the xml file not being parsed well

## environment
ran it on windows 10 and arch
both have openjdk17

## possible solution
if allowed will fix it since my main goal was to take care of previous issues on the issues page

**Comment by mwangidennis1** [comment]
saw reason for error

**Comment by samuelowino** [comment]
The project expected your input xml to have tags in the form

```xml
<resources>
<strings>Content</strings>
</resources>
```

**Comment by samuelowino** [comment]
Can you improve the error handling to make this a bit clearer?

**Comment by mwangidennis1** [comment]
I realized the conversion to File type happens  if  i do an instanceof and
so the error was in the format of my xml
mine: <string name="title"> hello world </string>
accepted  format was <strings name="title">hello world</strings>

**Comment by samuelowino** [comment]
You could add a `try-catch` block around the section where the failure occurs due to an incorrect format. Instead of allowing the error to propagate, log a more detailed error message with a descriptive stack trace. An `IOException` with a custom message should be sufficient in this case.

```java
try {
    // Code where the failure occurs
} catch (NullPointerException e) {
    log.error("Invalid XML format detected in the pre-translate input. Expected format: <strings></strings>. Please refer to the documentation for correct usage.", e);
}
```

This approach will provide more meaningful error information and help users resolve format-related issues more easily.

**Comment by mwangidennis1** [comment]
Fixed
